project:
  type: website
  output-dir: docs

website:
  title: " "
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projetos
        href: projects.qmd
      - text: Sobre
        href: about.qmd
      - text: Currículo
        href: cv.qmd
    right:
      - icon: github
        href: https://github.com/seu-usuario
        aria-label: GitHub
      - icon: linkedin
        href: https://linkedin.com/in/seu-usuario
        aria-label: LinkedIn
      - icon: envelope-fill
        href: mailto:seu-email@email.com
        aria-label: Email
      - text: Lattes
        href: http://lattes.cnpq.br/seu-lattes

page-footer:
  left: "© 2024 Seu Nome. Todos os direitos reservados."
  right:
    - icon: github
      href: https://github.com/seu-usuario
    - icon: linkedin
      href: https://linkedin.com/in/seu-usuario

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: false
    page-layout: full



